/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Checks */
        get: operations["list_checks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Check */
        get: operations["get_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks/{check_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Check History */
        get: operations["get_check_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BetweenCondition */
        BetweenCondition: {
            /** High */
            high: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "between";
            /** Low */
            low: number;
            /** Negated */
            negated: boolean;
            /** Text */
            text: string;
        };
        /**
         * CheckDetail
         * @description One check with its rule: what `GET /checks/{id}` serves.
         */
        CheckDetail: {
            /** Dataset */
            dataset: string;
            /** Datasource */
            datasource: string;
            /** Expression */
            expression: string;
            /** Id */
            id: string;
            latest: components["schemas"]["LatestResult"] | null;
            location: components["schemas"]["Location"];
            /** Metric */
            metric: string;
            /** Name */
            name: string;
            /** Owner */
            owner: string | null;
            rule: components["schemas"]["Rule"];
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /**
             * Unit
             * @enum {string}
             */
            unit: "count" | "percent" | "duration" | "number";
        };
        /** CheckList */
        CheckList: {
            /** Items */
            items: components["schemas"]["CheckSummary"][];
            /** Total */
            total: number;
        };
        /** CheckSummary */
        CheckSummary: {
            /** Dataset */
            dataset: string;
            /** Datasource */
            datasource: string;
            /** Expression */
            expression: string;
            /** Id */
            id: string;
            latest: components["schemas"]["LatestResult"] | null;
            location: components["schemas"]["Location"];
            /** Metric */
            metric: string;
            /** Name */
            name: string;
            /** Owner */
            owner: string | null;
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /**
             * Unit
             * @enum {string}
             */
            unit: "count" | "percent" | "duration" | "number";
        };
        /** CompareCondition */
        CompareCondition: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "compare";
            /**
             * Op
             * @enum {string}
             */
            op: "=" | "!=" | "<" | "<=" | ">" | ">=";
            /** Text */
            text: string;
            /** Value */
            value: number;
        };
        /** Counts */
        Counts: {
            /** Error */
            error: number;
            /** Fail */
            fail: number;
            /** Pass */
            pass: number;
            /** Skipped */
            skipped: number;
            /** Total */
            total: number;
            /** Warn */
            warn: number;
        };
        /** Datasource */
        Datasource: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** Diagnostic */
        Diagnostic: {
            location: components["schemas"]["Location"] | null;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** ErrorBody */
        ErrorBody: {
            error: components["schemas"]["ErrorInfo"];
        };
        /** ErrorInfo */
        ErrorInfo: {
            /**
             * Code
             * @enum {string}
             */
            code: "invalid_parameter" | "forbidden_host" | "not_found" | "method_not_allowed" | "internal_error" | "store_unavailable";
            /** Message */
            message: string;
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Dataset */
            dataset: string;
            /** Display Value */
            display_value: string;
            /** Duration Ms */
            duration_ms: number;
            /** Expression */
            expression: string;
            /** Message */
            message: string | null;
            /** Metric */
            metric: string;
            /** Name */
            name: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "warn" | "fail" | "error" | "skipped";
            /** Run Id */
            run_id: string;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Trigger */
            trigger: string;
            /** Unit */
            unit: ("count" | "percent" | "duration" | "number") | null;
            /** Value */
            value: number | null;
        };
        /** HistoryPage */
        HistoryPage: {
            /** Items */
            items: components["schemas"]["HistoryEntry"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * LastEvaluated
         * @description What the data last showed, when the latest result could not be evaluated.
         */
        LastEvaluated: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "warn" | "fail";
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** LatestResult */
        LatestResult: {
            /** Display Value */
            display_value: string;
            last_evaluated: components["schemas"]["LastEvaluated"] | null;
            /** Message */
            message: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "warn" | "fail" | "error" | "skipped";
            /** Run Id */
            run_id: string;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Trigger */
            trigger: string;
            /** Value */
            value: number | null;
        };
        /** Location */
        Location: {
            /** Column */
            column: number;
            /** File */
            file: string;
            /** Line */
            line: number;
        };
        /** Project */
        Project: {
            counts: components["schemas"]["ProjectCounts"];
            /** Datasources */
            datasources: components["schemas"]["Datasource"][];
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /**
             * Loaded At
             * Format: date-time
             */
            loaded_at: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** ProjectCounts */
        ProjectCounts: {
            /** Checks */
            checks: number;
            /** Datasets */
            datasets: number;
        };
        /**
         * Rule
         * @description The check's conditions as this server loaded them.
         *
         *     Built only from the parsed expectation and triggers — never from options
         *     such as `valid_values`, or from `where:`/`filter:` SQL.
         */
        Rule: {
            /** Expect */
            expect: (components["schemas"]["CompareCondition"] | components["schemas"]["BetweenCondition"]) | null;
            /** Fail */
            fail: (components["schemas"]["CompareCondition"] | components["schemas"]["BetweenCondition"]) | null;
            /** Warn */
            warn: (components["schemas"]["CompareCondition"] | components["schemas"]["BetweenCondition"]) | null;
        };
        /** Run */
        Run: {
            counts: components["schemas"]["Counts"];
            /** Exit Code */
            exit_code: number;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "warn" | "fail" | "error" | "skipped";
            /** Project */
            project: string;
            /** Selection */
            selection: {
                check_ids?: string[];
                datasources?: string[];
                excludes?: string[];
                paths?: string[];
                tags?: string[];
            } & {
                [key: string]: string[];
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Trigger */
            trigger: string;
            /** Version */
            version: string;
        };
        /** RunDetail */
        RunDetail: {
            counts: components["schemas"]["Counts"];
            /** Exit Code */
            exit_code: number;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "warn" | "fail" | "error" | "skipped";
            /** Project */
            project: string;
            /** Results */
            results: components["schemas"]["RunResultItem"][];
            /** Selection */
            selection: {
                check_ids?: string[];
                datasources?: string[];
                excludes?: string[];
                paths?: string[];
                tags?: string[];
            } & {
                [key: string]: string[];
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Trigger */
            trigger: string;
            /** Version */
            version: string;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["Run"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RunResultItem */
        RunResultItem: {
            /** Check Id */
            check_id: string;
            /** Dataset */
            dataset: string;
            /** Datasource */
            datasource: string;
            /** Display Value */
            display_value: string;
            /** Duration Ms */
            duration_ms: number;
            /** Expression */
            expression: string;
            /** Message */
            message: string | null;
            /** Metric */
            metric: string;
            /** Name */
            name: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "pass" | "warn" | "fail" | "error" | "skipped";
            /** Owner */
            owner: string | null;
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /** Value */
            value: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_checks: {
        parameters: {
            query?: {
                outcome?: ("pass" | "warn" | "fail" | "error" | "skipped" | "not_run")[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckList"];
                };
            };
            /** @description invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description forbidden host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_check: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDetail"];
                };
            };
            /** @description invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description forbidden host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_check_history: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            /** @description invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description forbidden host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description forbidden host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description forbidden host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description forbidden host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
